Give each test a proter class name
TestRooExcel reopens the class defined in test/test_roo_excel.rb, and overwrites

TestRooExcel is defined again in test/test_roo_excel.rb, and two test methods are overridden there.
This used to cause the following errors:

  .../roo-xls/test/test_roo_excel.rb:193: warning: method redefined; discarding old test_date_to_float_conversion
  .../roo-xls/test/test_excel_2003_xml.rb:26: warning: previous definition of test_date_to_float_conversion was here
  .../roo-xls/test/test_roo_excel.rb:238: warning: method redefined; discarding old test_ruby_spreadsheet_formula_bug
  .../roo-xls/test/test_excel_2003_xml.rb:35: warning: previous definition of test_ruby_spreadsheet_formula_bug was here

Now, this commit unveils two hidden tests both of which actually do not successfully finish.
Following is the errors from these resurrected tests:

  1) Error:
TestExcel2013XML#test_ruby_spreadsheet_formula_bug:
ArgumentError: Error: sheet 'nil' not valid
    .../roo/lib/roo/base.rb:573:in `validate_sheet!'
    .../roo-xls/lib/roo/xls/excel_2003_xml.rb:191:in `read_cells'
    .../roo-xls/lib/roo/xls/excel_2003_xml.rb:40:in `cell'
    .../roo-xls/test/test_excel_2003_xml.rb:37:in `block in test_ruby_spreadsheet_formula_bug'
    .../roo-xls/test/test_excel_2003_xml.rb:5:in `with_xml_spreadsheet'
    .../roo-xls/test/test_excel_2003_xml.rb:36:in `test_ruby_spreadsheet_formula_bug'

  2) Error:
TestExcel2013XML#test_date_to_float_conversion:
NoMethodError: undefined method `assert_nothing_raised' for #<TestExcel2013XML:0x00007fd74c41cf78>
Did you mean?  assert_contains
    .../roo-xls/test/test_excel_2003_xml.rb:28:in `block in test_date_to_float_conversion'
    .../roo-xls/test/test_excel_2003_xml.rb:5:in `with_xml_spreadsheet'
    .../roo-xls/test/test_excel_2003_xml.rb:27:in `test_date_to_float_conversion'